/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v2/HostedNumber/AuthorizationDocuments/{Sid}": {
    /** @description Fetch a specific AuthorizationDocument. */
    get: operations["FetchAuthorizationDocument"];
    /** @description Cancel the AuthorizationDocument request. */
    delete: operations["DeleteAuthorizationDocument"];
  };
  "/v2/HostedNumber/AuthorizationDocuments": {
    /** @description Retrieve a list of AuthorizationDocuments belonging to the account initiating the request. */
    get: operations["ListAuthorizationDocument"];
    /** @description Create an AuthorizationDocument for authorizing the hosting of phone number capabilities on Twilio's platform. */
    post: operations["CreateAuthorizationDocument"];
  };
  "/v2/HostedNumber/Orders/Bulk/{BulkHostingSid}": {
    /** @description Fetch a specific BulkHostedNumberOrder. */
    get: operations["FetchBulkHostedNumberOrder"];
  };
  "/v2/HostedNumber/Orders/Bulk": {
  };
  "/v2/RegulatoryCompliance/Bundles": {
    /** @description Retrieve a list of all Bundles for an account. */
    get: operations["ListBundle"];
    /** @description Create a new Bundle. */
    post: operations["CreateBundle"];
  };
  "/v2/RegulatoryCompliance/Bundles/{Sid}": {
    /** @description Fetch a specific Bundle instance. */
    get: operations["FetchBundle"];
    /** @description Updates a Bundle in an account. */
    post: operations["UpdateBundle"];
    /** @description Delete a specific Bundle. */
    delete: operations["DeleteBundle"];
  };
  "/v2/RegulatoryCompliance/Bundles/{BundleSid}/Copies": {
    /** @description Retrieve a list of all Bundles Copies for a Bundle. */
    get: operations["ListBundleCopy"];
    /** @description Creates a new copy of a Bundle. It will internally create copies of all the bundle items (identities and documents) of the original bundle */
    post: operations["CreateBundleCopy"];
  };
  "/v2/HostedNumber/AuthorizationDocuments/{SigningDocumentSid}/DependentHostedNumberOrders": {
    /** @description Retrieve a list of dependent HostedNumberOrders belonging to the AuthorizationDocument. */
    get: operations["ListDependentHostedNumberOrder"];
  };
  "/v2/RegulatoryCompliance/EndUsers": {
    /** @description Retrieve a list of all End User for an account. */
    get: operations["ListEndUser"];
    /** @description Create a new End User. */
    post: operations["CreateEndUser"];
  };
  "/v2/RegulatoryCompliance/EndUsers/{Sid}": {
    /** @description Fetch specific End User Instance. */
    get: operations["FetchEndUser"];
    /** @description Update an existing End User. */
    post: operations["UpdateEndUser"];
    /** @description Delete a specific End User. */
    delete: operations["DeleteEndUser"];
  };
  "/v2/RegulatoryCompliance/EndUserTypes": {
    /** @description Retrieve a list of all End-User Types. */
    get: operations["ListEndUserType"];
  };
  "/v2/RegulatoryCompliance/EndUserTypes/{Sid}": {
    /** @description Fetch a specific End-User Type Instance. */
    get: operations["FetchEndUserType"];
  };
  "/v2/RegulatoryCompliance/Bundles/{BundleSid}/Evaluations": {
    /** @description Retrieve a list of Evaluations associated to the Bundle resource. */
    get: operations["ListEvaluation"];
    /** @description Creates an evaluation for a bundle */
    post: operations["CreateEvaluation"];
  };
  "/v2/RegulatoryCompliance/Bundles/{BundleSid}/Evaluations/{Sid}": {
    /** @description Fetch specific Evaluation Instance. */
    get: operations["FetchEvaluation"];
  };
  "/v2/HostedNumber/Orders/{Sid}": {
    /** @description Fetch a specific HostedNumberOrder. */
    get: operations["FetchHostedNumberOrder"];
    /** @description Cancel the HostedNumberOrder (only available when the status is in `received`). */
    delete: operations["DeleteHostedNumberOrder"];
  };
  "/v2/HostedNumber/Orders": {
    /** @description Retrieve a list of HostedNumberOrders belonging to the account initiating the request. */
    get: operations["ListHostedNumberOrder"];
    /** @description Host a phone number's capability on Twilio's platform. */
    post: operations["CreateHostedNumberOrder"];
  };
  "/v2/RegulatoryCompliance/Bundles/{BundleSid}/ItemAssignments": {
    /** @description Retrieve a list of all Assigned Items for an account. */
    get: operations["ListItemAssignment"];
    /** @description Create a new Assigned Item. */
    post: operations["CreateItemAssignment"];
  };
  "/v2/RegulatoryCompliance/Bundles/{BundleSid}/ItemAssignments/{Sid}": {
    /** @description Fetch specific Assigned Item Instance. */
    get: operations["FetchItemAssignment"];
    /** @description Remove an Assignment Item Instance. */
    delete: operations["DeleteItemAssignment"];
  };
  "/v2/RegulatoryCompliance/Regulations": {
    /** @description Retrieve a list of all Regulations. */
    get: operations["ListRegulation"];
  };
  "/v2/RegulatoryCompliance/Regulations/{Sid}": {
    /** @description Fetch specific Regulation Instance. */
    get: operations["FetchRegulation"];
  };
  "/v2/RegulatoryCompliance": {
  };
  "/v2/RegulatoryCompliance/Bundles/{BundleSid}/ReplaceItems": {
    /** @description Replaces all bundle items in the target bundle (specified in the path) with all the bundle items of the source bundle (specified by the from_bundle_sid body param) */
    post: operations["CreateReplaceItems"];
  };
  "/v2/RegulatoryCompliance/SupportingDocuments": {
    /** @description Retrieve a list of all Supporting Document for an account. */
    get: operations["ListSupportingDocument"];
    /** @description Create a new Supporting Document. */
    post: operations["CreateSupportingDocument"];
  };
  "/v2/RegulatoryCompliance/SupportingDocuments/{Sid}": {
    /** @description Fetch specific Supporting Document Instance. */
    get: operations["FetchSupportingDocument"];
    /** @description Update an existing Supporting Document. */
    post: operations["UpdateSupportingDocument"];
    /** @description Delete a specific Supporting Document. */
    delete: operations["DeleteSupportingDocument"];
  };
  "/v2/RegulatoryCompliance/SupportingDocumentTypes": {
    /** @description Retrieve a list of all Supporting Document Types. */
    get: operations["ListSupportingDocumentType"];
  };
  "/v2/RegulatoryCompliance/SupportingDocumentTypes/{Sid}": {
    /** @description Fetch a specific Supporting Document Type Instance. */
    get: operations["FetchSupportingDocumentType"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "numbers.v2.authorization_document": {
      /** @description A 34 character string that uniquely identifies this AuthorizationDocument. */
      sid?: string | null;
      /** @description A 34 character string that uniquely identifies the Address resource that is associated with this AuthorizationDocument. */
      address_sid?: string | null;
      /** @description Status of an instance resource. It can hold one of the values: 1. opened 2. signing, 3. signed LOA, 4. canceled, 5. failed. See the section entitled [Status Values](https://www.twilio.com/docs/phone-numbers/hosted-numbers/hosted-numbers-api/authorization-document-resource#status-values) for more information on each of these statuses. */
      status?: components["schemas"]["authorization_document_enum_status"];
      /** @description Email that this AuthorizationDocument will be sent to for signing. */
      email?: string | null;
      /** @description Email recipients who will be informed when an Authorization Document has been sent and signed. */
      cc_emails?: string[] | null;
      /**
       * Format: date-time
       * @description The date this resource was created, given as [GMT RFC 2822](http://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date that this resource was updated, given as [GMT RFC 2822](http://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_updated?: string | null;
      /** Format: uri */
      url?: string | null;
      /** Format: uri-map */
      links?: Record<string, unknown> | null;
    };
    /** @enum {string} */
    authorization_document_enum_status: "opened" | "signing" | "signed" | "canceled" | "failed";
    "numbers.v2.bulk_hosted_number_order": {
      /** @description A 34 character string that uniquely identifies this BulkHostedNumberOrder. */
      bulk_hosting_sid?: string | null;
      /** @description A string that shows the status of the current Bulk Hosting request, it can vary between these values: 'QUEUED','IN_PROGRESS','PROCESSED' */
      request_status?: components["schemas"]["bulk_hosted_number_order_enum_request_status"];
      /** @description A 128 character string that is a human-readable text that describes this resource. */
      friendly_name?: string | null;
      /** @description Email address used for send notifications about this Bulk hosted number request. */
      notification_email?: string | null;
      /**
       * Format: date-time
       * @description The date this resource was created, given as [GMT RFC 2822](http://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date that this resource was completed, given as [GMT RFC 2822](http://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_completed?: string | null;
      /**
       * Format: uri
       * @description The URL of this BulkHostedNumberOrder resource.
       */
      url?: string | null;
      /** @description The total count of phone numbers in this Bulk hosting request. */
      total_count?: number | null;
      /** @description Contains a list of all the individual hosting orders and their information, for this Bulk request. Each result object is grouped by its order status. To see a complete list of order status, please check 'https://www.twilio.com/docs/phone-numbers/hosted-numbers/hosted-numbers-api/hosted-number-order-resource#status-values'. */
      results?: unknown[] | null;
    };
    /** @enum {string} */
    bulk_hosted_number_order_enum_request_status: "QUEUED" | "IN_PROGRESS" | "PROCESSED";
    "numbers.v2.regulatory_compliance.bundle": {
      /** @description The unique string that we created to identify the Bundle resource. */
      sid?: string | null;
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Bundle resource. */
      account_sid?: string | null;
      /** @description The unique string of a regulation that is associated to the Bundle resource. */
      regulation_sid?: string | null;
      /** @description The string that you assigned to describe the resource. */
      friendly_name?: string | null;
      /** @description The verification status of the Bundle resource. */
      status?: components["schemas"]["bundle_enum_status"];
      /**
       * Format: date-time
       * @description The date and time in GMT in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format when the resource will be valid until.
       */
      valid_until?: string | null;
      /** @description The email address that will receive updates when the Bundle resource changes status. */
      email?: string | null;
      /**
       * Format: uri
       * @description The URL we call to inform your application of status changes.
       */
      status_callback?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null;
      /**
       * Format: uri
       * @description The absolute URL of the Bundle resource.
       */
      url?: string | null;
      /**
       * Format: uri-map
       * @description The URLs of the Assigned Items of the Bundle resource.
       */
      links?: Record<string, unknown> | null;
    };
    /** @enum {string} */
    bundle_enum_status: "draft" | "pending-review" | "in-review" | "twilio-rejected" | "twilio-approved" | "provisionally-approved";
    /** @enum {string} */
    bundle_enum_end_user_type: "individual" | "business";
    /** @enum {string} */
    bundle_enum_sort_by: "valid-until" | "date-updated";
    /** @enum {string} */
    bundle_enum_sort_direction: "ASC" | "DESC";
    "numbers.v2.regulatory_compliance.bundle.bundle_copy": {
      /** @description The unique string that we created to identify the Bundle resource. */
      sid?: string | null;
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Bundle resource. */
      account_sid?: string | null;
      /** @description The unique string of a regulation that is associated to the Bundle resource. */
      regulation_sid?: string | null;
      /** @description The string that you assigned to describe the resource. */
      friendly_name?: string | null;
      /** @description The verification status of the Bundle resource. */
      status?: components["schemas"]["bundle_copy_enum_status"];
      /**
       * Format: date-time
       * @description The date and time in GMT in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format when the resource will be valid until.
       */
      valid_until?: string | null;
      /** @description The email address that will receive updates when the Bundle resource changes status. */
      email?: string | null;
      /**
       * Format: uri
       * @description The URL we call to inform your application of status changes.
       */
      status_callback?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null;
    };
    /** @enum {string} */
    bundle_copy_enum_status: "draft" | "pending-review" | "in-review" | "twilio-rejected" | "twilio-approved" | "provisionally-approved";
    /** @enum {string} */
    bundle_copy_enum_end_user_type: "individual" | "business";
    "numbers.v2.authorization_document.dependent_hosted_number_order": {
      /** @description A 34 character string that uniquely identifies this Authorization Document */
      sid?: string | null;
      /** @description A 34 character string that uniquely identifies the bulk hosting request associated with this HostedNumberOrder. */
      bulk_hosting_request_sid?: string | null;
      /** @description The next step you need to take to complete the hosted number order and request it successfully. */
      next_step?: string | null;
      /** @description The unique SID identifier of the Account. */
      account_sid?: string | null;
      /** @description A 34 character string that uniquely identifies the IncomingPhoneNumber resource created by this HostedNumberOrder. */
      incoming_phone_number_sid?: string | null;
      /** @description A 34 character string that uniquely identifies the Address resource that represents the address of the owner of this phone number. */
      address_sid?: string | null;
      /** @description A 34 character string that uniquely identifies the LOA document associated with this HostedNumberOrder. */
      signing_document_sid?: string | null;
      /**
       * Format: phone-number
       * @description An E164 formatted phone number hosted by this HostedNumberOrder.
       */
      phone_number?: string | null;
      /**
       * Format: phone-number-capabilities
       * @description A mapping of capabilities this hosted phone number will have enabled on Twilio's platform.
       */
      capabilities?: {
        mms?: boolean;
        sms?: boolean;
        voice?: boolean;
        fax?: boolean;
      } | null;
      /** @description A human readable description of this resource, up to 128 characters. */
      friendly_name?: string | null;
      /** @description Status of an instance resource. It can hold one of the values: 1. opened 2. signing, 3. signed LOA, 4. canceled, 5. failed. See the section entitled [Status Values](https://www.twilio.com/docs/phone-numbers/hosted-numbers/hosted-numbers-api/authorization-document-resource#status-values) for more information on each of these statuses. */
      status?: components["schemas"]["dependent_hosted_number_order_enum_status"];
      /** @description A message that explains why a hosted_number_order went to status "action-required" */
      failure_reason?: string | null;
      /**
       * Format: date-time
       * @description The date this resource was created, given as [GMT RFC 2822](http://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date that this resource was updated, given as [GMT RFC 2822](http://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_updated?: string | null;
      /** @description Email of the owner of this phone number that is being hosted. */
      email?: string | null;
      /** @description Email recipients who will be informed when an Authorization Document has been sent and signed */
      cc_emails?: string[] | null;
      /** @description The title of the person authorized to sign the Authorization Document for this phone number. */
      contact_title?: string | null;
      /**
       * Format: phone-number
       * @description The contact phone number of the person authorized to sign the Authorization Document.
       */
      contact_phone_number?: string | null;
    };
    /** @enum {string} */
    dependent_hosted_number_order_enum_status: "received" | "verified" | "pending-loa" | "carrier-processing" | "completed" | "failed" | "action-required";
    "numbers.v2.regulatory_compliance.end_user": {
      /** @description The unique string created by Twilio to identify the End User resource. */
      sid?: string | null;
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the End User resource. */
      account_sid?: string | null;
      /** @description The string that you assigned to describe the resource. */
      friendly_name?: string | null;
      /** @description The type of end user of the Bundle resource - can be `individual` or `business`. */
      type?: components["schemas"]["end_user_enum_type"];
      /** @description The set of parameters that are the attributes of the End Users resource which are listed in the End User Types. */
      attributes?: unknown;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null;
      /**
       * Format: uri
       * @description The absolute URL of the End User resource.
       */
      url?: string | null;
    };
    /** @enum {string} */
    end_user_enum_type: "individual" | "business";
    "numbers.v2.regulatory_compliance.end_user_type": {
      /** @description The unique string that identifies the End-User Type resource. */
      sid?: string | null;
      /** @description A human-readable description that is assigned to describe the End-User Type resource. Examples can include first name, last name, email, business name, etc */
      friendly_name?: string | null;
      /** @description A machine-readable description of the End-User Type resource. Examples can include first_name, last_name, email, business_name, etc. */
      machine_name?: string | null;
      /** @description The required information for creating an End-User. The required fields will change as regulatory needs change and will differ for businesses and individuals. */
      fields?: unknown[] | null;
      /**
       * Format: uri
       * @description The absolute URL of the End-User Type resource.
       */
      url?: string | null;
    };
    "numbers.v2.regulatory_compliance.bundle.evaluation": {
      /** @description The unique string that identifies the Evaluation resource. */
      sid?: string | null;
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Bundle resource. */
      account_sid?: string | null;
      /** @description The unique string of a regulation that is associated to the Bundle resource. */
      regulation_sid?: string | null;
      /** @description The unique string that we created to identify the Bundle resource. */
      bundle_sid?: string | null;
      /** @description The compliance status of the Evaluation resource. */
      status?: components["schemas"]["evaluation_enum_status"];
      /** @description The results of the Evaluation which includes the valid and invalid attributes. */
      results?: unknown[] | null;
      /** Format: date-time */
      date_created?: string | null;
      /** Format: uri */
      url?: string | null;
    };
    /** @enum {string} */
    evaluation_enum_status: "compliant" | "noncompliant";
    "numbers.v2.hosted_number_order": {
      /** @description A 34 character string that uniquely identifies this HostedNumberOrder. */
      sid?: string | null;
      /** @description A 34 character string that uniquely identifies the account. */
      account_sid?: string | null;
      /** @description A 34 character string that uniquely identifies the [IncomingPhoneNumber](https://www.twilio.com/docs/phone-numbers/api/incomingphonenumber-resource) resource that represents the phone number being hosted. */
      incoming_phone_number_sid?: string | null;
      /** @description A 34 character string that uniquely identifies the Address resource that represents the address of the owner of this phone number. */
      address_sid?: string | null;
      /** @description A 34 character string that uniquely identifies the [Authorization Document](https://www.twilio.com/docs/phone-numbers/hosted-numbers/hosted-numbers-api/authorization-document-resource) the user needs to sign. */
      signing_document_sid?: string | null;
      /**
       * Format: phone-number
       * @description Phone number to be hosted. This must be in [E.164](https://en.wikipedia.org/wiki/E.164) format, e.g., +16175551212
       */
      phone_number?: string | null;
      /**
       * Format: phone-number-capabilities
       * @description Set of booleans describing the capabilities hosted on Twilio's platform. SMS is currently only supported.
       */
      capabilities?: {
        mms?: boolean;
        sms?: boolean;
        voice?: boolean;
        fax?: boolean;
      } | null;
      /** @description A 128 character string that is a human-readable text that describes this resource. */
      friendly_name?: string | null;
      /** @description Status of this resource. It can hold one of the values: 1. Twilio Processing 2. Received, 3. Pending LOA, 4. Carrier Processing, 5. Completed, 6. Action Required, 7. Failed. See the [HostedNumberOrders Status Values](https://www.twilio.com/docs/phone-numbers/hosted-numbers/hosted-numbers-api/hosted-number-order-resource#status-values) section for more information on each of these statuses. */
      status?: components["schemas"]["hosted_number_order_enum_status"];
      /** @description A message that explains why a hosted_number_order went to status "action-required" */
      failure_reason?: string | null;
      /**
       * Format: date-time
       * @description The date this resource was created, given as [GMT RFC 2822](http://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date that this resource was updated, given as [GMT RFC 2822](http://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_updated?: string | null;
      /** @description Email of the owner of this phone number that is being hosted. */
      email?: string | null;
      /** @description A list of emails that LOA document for this HostedNumberOrder will be carbon copied to. */
      cc_emails?: string[] | null;
      /**
       * Format: uri
       * @description The URL of this HostedNumberOrder.
       */
      url?: string | null;
      /** @description The title of the person authorized to sign the Authorization Document for this phone number. */
      contact_title?: string | null;
      /**
       * Format: phone-number
       * @description The contact phone number of the person authorized to sign the Authorization Document.
       */
      contact_phone_number?: string | null;
      /** @description A 34 character string that uniquely identifies the bulk hosting request associated with this HostedNumberOrder. */
      bulk_hosting_request_sid?: string | null;
      /** @description The next step you need to take to complete the hosted number order and request it successfully. */
      next_step?: string | null;
    };
    /** @enum {string} */
    hosted_number_order_enum_status: "received" | "verified" | "pending-loa" | "carrier-processing" | "completed" | "failed" | "action-required";
    "numbers.v2.regulatory_compliance.bundle.item_assignment": {
      /** @description The unique string that we created to identify the Item Assignment resource. */
      sid?: string | null;
      /** @description The unique string that we created to identify the Bundle resource. */
      bundle_sid?: string | null;
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Item Assignment resource. */
      account_sid?: string | null;
      /** @description The SID of an object bag that holds information of the different items. */
      object_sid?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null;
      /**
       * Format: uri
       * @description The absolute URL of the Identity resource.
       */
      url?: string | null;
    };
    "numbers.v2.regulatory_compliance.regulation": {
      /** @description The unique string that identifies the Regulation resource. */
      sid?: string | null;
      /** @description A human-readable description that is assigned to describe the Regulation resource. Examples can include Germany: Mobile - Business. */
      friendly_name?: string | null;
      /** @description The ISO country code of the phone number's country. */
      iso_country?: string | null;
      /** @description The type of phone number restricted by the regulatory requirement. For example, Germany mobile phone numbers provisioned by businesses require a business name with commercial register proof from the Handelsregisterauszug and a proof of address from Handelsregisterauszug or a trade license by Gewerbeanmeldung. */
      number_type?: string | null;
      /** @description The type of End User the regulation requires - can be `individual` or `business`. */
      end_user_type?: components["schemas"]["regulation_enum_end_user_type"];
      /** @description The SID of an object that holds the regulatory information of the phone number country, phone number type, and end user type. */
      requirements?: unknown;
      /**
       * Format: uri
       * @description The absolute URL of the Regulation resource.
       */
      url?: string | null;
    };
    /** @enum {string} */
    regulation_enum_end_user_type: "individual" | "business";
    "numbers.v2.regulatory_compliance": Record<string, never>;
    "numbers.v2.regulatory_compliance.bundle.replace_items": {
      /** @description The unique string that we created to identify the Bundle resource. */
      sid?: string | null;
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Bundle resource. */
      account_sid?: string | null;
      /** @description The unique string of a regulation that is associated to the Bundle resource. */
      regulation_sid?: string | null;
      /** @description The string that you assigned to describe the resource. */
      friendly_name?: string | null;
      /** @description The verification status of the Bundle resource. */
      status?: components["schemas"]["replace_items_enum_status"];
      /**
       * Format: date-time
       * @description The date and time in GMT in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format when the resource will be valid until.
       */
      valid_until?: string | null;
      /** @description The email address that will receive updates when the Bundle resource changes status. */
      email?: string | null;
      /**
       * Format: uri
       * @description The URL we call to inform your application of status changes.
       */
      status_callback?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null;
    };
    /** @enum {string} */
    replace_items_enum_status: "draft" | "pending-review" | "in-review" | "twilio-rejected" | "twilio-approved" | "provisionally-approved";
    /** @enum {string} */
    replace_items_enum_end_user_type: "individual" | "business";
    "numbers.v2.regulatory_compliance.supporting_document": {
      /** @description The unique string created by Twilio to identify the Supporting Document resource. */
      sid?: string | null;
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Document resource. */
      account_sid?: string | null;
      /** @description The string that you assigned to describe the resource. */
      friendly_name?: string | null;
      /** @description The image type uploaded in the Supporting Document container. */
      mime_type?: string | null;
      /** @description The verification status of the Supporting Document resource. */
      status?: components["schemas"]["supporting_document_enum_status"];
      /** @description The failure reason of the Supporting Document Resource. */
      failure_reason?: string | null;
      /** @description The type of the Supporting Document. */
      type?: string | null;
      /** @description The set of parameters that are the attributes of the Supporting Documents resource which are listed in the Supporting Document Types. */
      attributes?: unknown;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null;
      /**
       * Format: uri
       * @description The absolute URL of the Supporting Document resource.
       */
      url?: string | null;
    };
    /** @enum {string} */
    supporting_document_enum_status: "draft" | "pending-review" | "rejected" | "approved" | "expired" | "provisionally-approved";
    "numbers.v2.regulatory_compliance.supporting_document_type": {
      /** @description The unique string that identifies the Supporting Document Type resource. */
      sid?: string | null;
      /** @description A human-readable description of the Supporting Document Type resource. */
      friendly_name?: string | null;
      /** @description The machine-readable description of the Supporting Document Type resource. */
      machine_name?: string | null;
      /** @description The required information for creating a Supporting Document. The required fields will change as regulatory needs change and will differ for businesses and individuals. */
      fields?: unknown[] | null;
      /**
       * Format: uri
       * @description The absolute URL of the Supporting Document Type resource.
       */
      url?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** @description Fetch a specific AuthorizationDocument. */
  FetchAuthorizationDocument: {
    parameters: {
      path: {
        /** @description A 34 character string that uniquely identifies this AuthorizationDocument. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.authorization_document"];
        };
      };
    };
  };
  /** @description Cancel the AuthorizationDocument request. */
  DeleteAuthorizationDocument: {
    parameters: {
      path: {
        /** @description A 34 character string that uniquely identifies this AuthorizationDocument. */
        Sid: string;
      };
    };
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never;
      };
    };
  };
  /** @description Retrieve a list of AuthorizationDocuments belonging to the account initiating the request. */
  ListAuthorizationDocument: {
    parameters: {
      query?: {
        /** @description Email that this AuthorizationDocument will be sent to for signing. */
        Email?: string;
        /** @description Status of an instance resource. It can hold one of the values: 1. opened 2. signing, 3. signed LOA, 4. canceled, 5. failed. See the section entitled [Status Values](https://www.twilio.com/docs/phone-numbers/hosted-numbers/hosted-numbers-api/authorization-document-resource#status-values) for more information on each of these statuses. */
        Status?: components["schemas"]["authorization_document_enum_status"];
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            items?: components["schemas"]["numbers.v2.authorization_document"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Create an AuthorizationDocument for authorizing the hosting of phone number capabilities on Twilio's platform. */
  CreateAuthorizationDocument: {
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description A 34 character string that uniquely identifies the Address resource that is associated with this AuthorizationDocument. */
          AddressSid: string;
          /** @description Email that this AuthorizationDocument will be sent to for signing. */
          Email: string;
          /**
           * Format: phone-number
           * @description The contact phone number of the person authorized to sign the Authorization Document.
           */
          ContactPhoneNumber: string;
          /** @description A list of HostedNumberOrder sids that this AuthorizationDocument will authorize for hosting phone number capabilities on Twilio's platform. */
          HostedNumberOrderSids: string[];
          /** @description The title of the person authorized to sign the Authorization Document for this phone number. */
          ContactTitle?: string;
          /** @description Email recipients who will be informed when an Authorization Document has been sent and signed. */
          CcEmails?: string[];
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["numbers.v2.authorization_document"];
        };
      };
    };
  };
  /** @description Fetch a specific BulkHostedNumberOrder. */
  FetchBulkHostedNumberOrder: {
    parameters: {
      query?: {
        /** @description Order status can be used for filtering on Hosted Number Order status values. To see a complete list of order statuses, please check 'https://www.twilio.com/docs/phone-numbers/hosted-numbers/hosted-numbers-api/hosted-number-order-resource#status-values'. */
        OrderStatus?: string;
      };
      path: {
        /** @description A 34 character string that uniquely identifies this BulkHostedNumberOrder. */
        BulkHostingSid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.bulk_hosted_number_order"];
        };
      };
    };
  };
  /** @description Retrieve a list of all Bundles for an account. */
  ListBundle: {
    parameters: {
      query?: {
        /** @description The verification status of the Bundle resource. Please refer to [Bundle Statuses](https://www.twilio.com/docs/phone-numbers/regulatory/api/bundles#bundle-statuses) for more details. */
        Status?: components["schemas"]["bundle_enum_status"];
        /** @description The string that you assigned to describe the resource. The column can contain 255 variable characters. */
        FriendlyName?: string;
        /** @description The unique string of a [Regulation resource](https://www.twilio.com/docs/phone-numbers/regulatory/api/regulations) that is associated to the Bundle resource. */
        RegulationSid?: string;
        /** @description The 2-digit [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the Bundle's phone number country ownership request. */
        IsoCountry?: string;
        /** @description The type of phone number of the Bundle's ownership request. Can be `local`, `mobile`, `national`, or `tollfree`. */
        NumberType?: string;
        /** @description Indicates that the Bundle is a valid Bundle until a specified expiration date. */
        HasValidUntilDate?: boolean;
        /** @description Can be `valid-until` or `date-updated`. Defaults to `date-created`. */
        SortBy?: components["schemas"]["bundle_enum_sort_by"];
        /** @description Default is `DESC`. Can be `ASC` or `DESC`. */
        SortDirection?: components["schemas"]["bundle_enum_sort_direction"];
        /** @description Date to filter Bundles having their `valid_until_date` before or after the specified date. Can be `ValidUntilDate>=` or `ValidUntilDate<=`. Both can be used in conjunction as well. [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) is the acceptable date format. */
        ValidUntilDate?: string;
        /** @description Date to filter Bundles having their `valid_until_date` before or after the specified date. Can be `ValidUntilDate>=` or `ValidUntilDate<=`. Both can be used in conjunction as well. [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) is the acceptable date format. */
        "ValidUntilDate<"?: string;
        /** @description Date to filter Bundles having their `valid_until_date` before or after the specified date. Can be `ValidUntilDate>=` or `ValidUntilDate<=`. Both can be used in conjunction as well. [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) is the acceptable date format. */
        "ValidUntilDate>"?: string;
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            results?: components["schemas"]["numbers.v2.regulatory_compliance.bundle"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Create a new Bundle. */
  CreateBundle: {
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description The string that you assigned to describe the resource. */
          FriendlyName: string;
          /** @description The email address that will receive updates when the Bundle resource changes status. */
          Email: string;
          /**
           * Format: uri
           * @description The URL we call to inform your application of status changes.
           */
          StatusCallback?: string;
          /** @description The unique string of a regulation that is associated to the Bundle resource. */
          RegulationSid?: string;
          /** @description The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the Bundle's phone number country ownership request. */
          IsoCountry?: string;
          /** @description The [type of End User](https://www.twilio.com/docs/phone-numbers/regulatory/api/end-user-types) of the Bundle resource. */
          EndUserType?: components["schemas"]["bundle_enum_end_user_type"];
          /** @description The type of phone number of the Bundle's ownership request. Can be `local`, `mobile`, `national`, or `toll free`. */
          NumberType?: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.bundle"];
        };
      };
    };
  };
  /** @description Fetch a specific Bundle instance. */
  FetchBundle: {
    parameters: {
      path: {
        /** @description The unique string that we created to identify the Bundle resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.bundle"];
        };
      };
    };
  };
  /** @description Updates a Bundle in an account. */
  UpdateBundle: {
    parameters: {
      path: {
        /** @description The unique string that we created to identify the Bundle resource. */
        Sid: string;
      };
    };
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description The verification status of the Bundle resource. */
          Status?: components["schemas"]["bundle_enum_status"];
          /**
           * Format: uri
           * @description The URL we call to inform your application of status changes.
           */
          StatusCallback?: string;
          /** @description The string that you assigned to describe the resource. */
          FriendlyName?: string;
          /** @description The email address that will receive updates when the Bundle resource changes status. */
          Email?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.bundle"];
        };
      };
    };
  };
  /** @description Delete a specific Bundle. */
  DeleteBundle: {
    parameters: {
      path: {
        /** @description The unique string that we created to identify the Bundle resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never;
      };
    };
  };
  /** @description Retrieve a list of all Bundles Copies for a Bundle. */
  ListBundleCopy: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
      path: {
        /** @description The unique string that we created to identify the Bundle resource. */
        BundleSid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            results?: components["schemas"]["numbers.v2.regulatory_compliance.bundle.bundle_copy"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Creates a new copy of a Bundle. It will internally create copies of all the bundle items (identities and documents) of the original bundle */
  CreateBundleCopy: {
    parameters: {
      path: {
        /** @description The unique string that identifies the Bundle to be copied. */
        BundleSid: string;
      };
    };
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description The string that you assigned to describe the copied bundle. */
          FriendlyName?: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.bundle.bundle_copy"];
        };
      };
    };
  };
  /** @description Retrieve a list of dependent HostedNumberOrders belonging to the AuthorizationDocument. */
  ListDependentHostedNumberOrder: {
    parameters: {
      query?: {
        /** @description Status of an instance resource. It can hold one of the values: 1. opened 2. signing, 3. signed LOA, 4. canceled, 5. failed. See the section entitled [Status Values](https://www.twilio.com/docs/phone-numbers/hosted-numbers/hosted-numbers-api/authorization-document-resource#status-values) for more information on each of these statuses. */
        Status?: components["schemas"]["dependent_hosted_number_order_enum_status"];
        /** @description An E164 formatted phone number hosted by this HostedNumberOrder. */
        PhoneNumber?: string;
        /** @description A 34 character string that uniquely identifies the IncomingPhoneNumber resource created by this HostedNumberOrder. */
        IncomingPhoneNumberSid?: string;
        /** @description A human readable description of this resource, up to 128 characters. */
        FriendlyName?: string;
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
      path: {
        /** @description A 34 character string that uniquely identifies the LOA document associated with this HostedNumberOrder. */
        SigningDocumentSid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            items?: components["schemas"]["numbers.v2.authorization_document.dependent_hosted_number_order"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Retrieve a list of all End User for an account. */
  ListEndUser: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            results?: components["schemas"]["numbers.v2.regulatory_compliance.end_user"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Create a new End User. */
  CreateEndUser: {
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description The string that you assigned to describe the resource. */
          FriendlyName: string;
          /** @description The type of end user of the Bundle resource - can be `individual` or `business`. */
          Type: components["schemas"]["end_user_enum_type"];
          /** @description The set of parameters that are the attributes of the End User resource which are derived End User Types. */
          Attributes?: unknown;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.end_user"];
        };
      };
    };
  };
  /** @description Fetch specific End User Instance. */
  FetchEndUser: {
    parameters: {
      path: {
        /** @description The unique string created by Twilio to identify the End User resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.end_user"];
        };
      };
    };
  };
  /** @description Update an existing End User. */
  UpdateEndUser: {
    parameters: {
      path: {
        /** @description The unique string created by Twilio to identify the End User resource. */
        Sid: string;
      };
    };
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description The string that you assigned to describe the resource. */
          FriendlyName?: string;
          /** @description The set of parameters that are the attributes of the End User resource which are derived End User Types. */
          Attributes?: unknown;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.end_user"];
        };
      };
    };
  };
  /** @description Delete a specific End User. */
  DeleteEndUser: {
    parameters: {
      path: {
        /** @description The unique string created by Twilio to identify the End User resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never;
      };
    };
  };
  /** @description Retrieve a list of all End-User Types. */
  ListEndUserType: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            end_user_types?: components["schemas"]["numbers.v2.regulatory_compliance.end_user_type"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Fetch a specific End-User Type Instance. */
  FetchEndUserType: {
    parameters: {
      path: {
        /** @description The unique string that identifies the End-User Type resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.end_user_type"];
        };
      };
    };
  };
  /** @description Retrieve a list of Evaluations associated to the Bundle resource. */
  ListEvaluation: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
      path: {
        /** @description The unique string that identifies the Bundle resource. */
        BundleSid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            results?: components["schemas"]["numbers.v2.regulatory_compliance.bundle.evaluation"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Creates an evaluation for a bundle */
  CreateEvaluation: {
    parameters: {
      path: {
        /** @description The unique string that identifies the Bundle resource. */
        BundleSid: string;
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.bundle.evaluation"];
        };
      };
    };
  };
  /** @description Fetch specific Evaluation Instance. */
  FetchEvaluation: {
    parameters: {
      path: {
        /** @description The unique string that we created to identify the Bundle resource. */
        BundleSid: string;
        /** @description The unique string that identifies the Evaluation resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.bundle.evaluation"];
        };
      };
    };
  };
  /** @description Fetch a specific HostedNumberOrder. */
  FetchHostedNumberOrder: {
    parameters: {
      path: {
        /** @description A 34 character string that uniquely identifies this HostedNumberOrder. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.hosted_number_order"];
        };
      };
    };
  };
  /** @description Cancel the HostedNumberOrder (only available when the status is in `received`). */
  DeleteHostedNumberOrder: {
    parameters: {
      path: {
        /** @description A 34 character string that uniquely identifies this HostedNumberOrder. */
        Sid: string;
      };
    };
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never;
      };
    };
  };
  /** @description Retrieve a list of HostedNumberOrders belonging to the account initiating the request. */
  ListHostedNumberOrder: {
    parameters: {
      query?: {
        /** @description The Status of this HostedNumberOrder. One of `received`, `pending-verification`, `verified`, `pending-loa`, `carrier-processing`, `testing`, `completed`, `failed`, or `action-required`. */
        Status?: components["schemas"]["hosted_number_order_enum_status"];
        /** @description Whether the SMS capability will be hosted on our platform. Can be `true` of `false`. */
        SmsCapability?: boolean;
        /** @description An E164 formatted phone number hosted by this HostedNumberOrder. */
        PhoneNumber?: string;
        /** @description A 34 character string that uniquely identifies the IncomingPhoneNumber resource created by this HostedNumberOrder. */
        IncomingPhoneNumberSid?: string;
        /** @description A human readable description of this resource, up to 128 characters. */
        FriendlyName?: string;
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            items?: components["schemas"]["numbers.v2.hosted_number_order"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Host a phone number's capability on Twilio's platform. */
  CreateHostedNumberOrder: {
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /**
           * Format: phone-number
           * @description The number to host in [+E.164](https://en.wikipedia.org/wiki/E.164) format
           */
          PhoneNumber: string;
          /**
           * Format: phone-number
           * @description The contact phone number of the person authorized to sign the Authorization Document.
           */
          ContactPhoneNumber: string;
          /** @description Optional. A 34 character string that uniquely identifies the Address resource that represents the address of the owner of this phone number. */
          AddressSid: string;
          /** @description Optional. Email of the owner of this phone number that is being hosted. */
          Email: string;
          /** @description This defaults to the AccountSid of the authorization the user is using. This can be provided to specify a subaccount to add the HostedNumberOrder to. */
          AccountSid?: string;
          /** @description A 128 character string that is a human readable text that describes this resource. */
          FriendlyName?: string;
          /** @description Optional. A list of emails that the LOA document for this HostedNumberOrder will be carbon copied to. */
          CcEmails?: string[];
          /**
           * Format: uri
           * @description The URL that Twilio should request when somebody sends an SMS to the phone number. This will be copied onto the IncomingPhoneNumber resource.
           */
          SmsUrl?: string;
          /**
           * Format: http-method
           * @description The HTTP method that should be used to request the SmsUrl. Must be either `GET` or `POST`.  This will be copied onto the IncomingPhoneNumber resource.
           * @enum {string}
           */
          SmsMethod?: "GET" | "POST";
          /**
           * Format: uri
           * @description A URL that Twilio will request if an error occurs requesting or executing the TwiML defined by SmsUrl. This will be copied onto the IncomingPhoneNumber resource.
           */
          SmsFallbackUrl?: string;
          /** @description Used to specify that the SMS capability will be hosted on Twilio's platform. */
          SmsCapability?: boolean;
          /**
           * Format: http-method
           * @description The HTTP method that should be used to request the SmsFallbackUrl. Must be either `GET` or `POST`. This will be copied onto the IncomingPhoneNumber resource.
           * @enum {string}
           */
          SmsFallbackMethod?: "GET" | "POST";
          /**
           * Format: uri
           * @description Optional. The Status Callback URL attached to the IncomingPhoneNumber resource.
           */
          StatusCallbackUrl?: string;
          /**
           * Format: http-method
           * @description Optional. The Status Callback Method attached to the IncomingPhoneNumber resource.
           * @enum {string}
           */
          StatusCallbackMethod?: "GET" | "POST";
          /** @description Optional. The 34 character sid of the application Twilio should use to handle SMS messages sent to this number. If a `SmsApplicationSid` is present, Twilio will ignore all of the SMS urls above and use those set on the application. */
          SmsApplicationSid?: string;
          /** @description The title of the person authorized to sign the Authorization Document for this phone number. */
          ContactTitle?: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["numbers.v2.hosted_number_order"];
        };
      };
    };
  };
  /** @description Retrieve a list of all Assigned Items for an account. */
  ListItemAssignment: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
      path: {
        /** @description The unique string that we created to identify the Bundle resource. */
        BundleSid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            results?: components["schemas"]["numbers.v2.regulatory_compliance.bundle.item_assignment"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Create a new Assigned Item. */
  CreateItemAssignment: {
    parameters: {
      path: {
        /** @description The unique string that we created to identify the Bundle resource. */
        BundleSid: string;
      };
    };
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description The SID of an object bag that holds information of the different items. */
          ObjectSid: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.bundle.item_assignment"];
        };
      };
    };
  };
  /** @description Fetch specific Assigned Item Instance. */
  FetchItemAssignment: {
    parameters: {
      path: {
        /** @description The unique string that we created to identify the Bundle resource. */
        BundleSid: string;
        /** @description The unique string that we created to identify the Identity resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.bundle.item_assignment"];
        };
      };
    };
  };
  /** @description Remove an Assignment Item Instance. */
  DeleteItemAssignment: {
    parameters: {
      path: {
        /** @description The unique string that we created to identify the Bundle resource. */
        BundleSid: string;
        /** @description The unique string that we created to identify the Identity resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never;
      };
    };
  };
  /** @description Retrieve a list of all Regulations. */
  ListRegulation: {
    parameters: {
      query?: {
        /** @description The type of End User the regulation requires - can be `individual` or `business`. */
        EndUserType?: components["schemas"]["regulation_enum_end_user_type"];
        /** @description The ISO country code of the phone number's country. */
        IsoCountry?: string;
        /** @description The type of phone number that the regulatory requiremnt is restricting. */
        NumberType?: string;
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            results?: components["schemas"]["numbers.v2.regulatory_compliance.regulation"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Fetch specific Regulation Instance. */
  FetchRegulation: {
    parameters: {
      path: {
        /** @description The unique string that identifies the Regulation resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.regulation"];
        };
      };
    };
  };
  /** @description Replaces all bundle items in the target bundle (specified in the path) with all the bundle items of the source bundle (specified by the from_bundle_sid body param) */
  CreateReplaceItems: {
    parameters: {
      path: {
        /** @description The unique string that identifies the Bundle where the item assignments are going to be replaced. */
        BundleSid: string;
      };
    };
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description The source bundle sid to copy the item assignments from. */
          FromBundleSid: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.bundle.replace_items"];
        };
      };
    };
  };
  /** @description Retrieve a list of all Supporting Document for an account. */
  ListSupportingDocument: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            results?: components["schemas"]["numbers.v2.regulatory_compliance.supporting_document"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Create a new Supporting Document. */
  CreateSupportingDocument: {
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description The string that you assigned to describe the resource. */
          FriendlyName: string;
          /** @description The type of the Supporting Document. */
          Type: string;
          /** @description The set of parameters that are the attributes of the Supporting Documents resource which are derived Supporting Document Types. */
          Attributes?: unknown;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.supporting_document"];
        };
      };
    };
  };
  /** @description Fetch specific Supporting Document Instance. */
  FetchSupportingDocument: {
    parameters: {
      path: {
        /** @description The unique string created by Twilio to identify the Supporting Document resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.supporting_document"];
        };
      };
    };
  };
  /** @description Update an existing Supporting Document. */
  UpdateSupportingDocument: {
    parameters: {
      path: {
        /** @description The unique string created by Twilio to identify the Supporting Document resource. */
        Sid: string;
      };
    };
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description The string that you assigned to describe the resource. */
          FriendlyName?: string;
          /** @description The set of parameters that are the attributes of the Supporting Document resource which are derived Supporting Document Types. */
          Attributes?: unknown;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.supporting_document"];
        };
      };
    };
  };
  /** @description Delete a specific Supporting Document. */
  DeleteSupportingDocument: {
    parameters: {
      path: {
        /** @description The unique string created by Twilio to identify the Supporting Document resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never;
      };
    };
  };
  /** @description Retrieve a list of all Supporting Document Types. */
  ListSupportingDocumentType: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            supporting_document_types?: components["schemas"]["numbers.v2.regulatory_compliance.supporting_document_type"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Fetch a specific Supporting Document Type Instance. */
  FetchSupportingDocumentType: {
    parameters: {
      path: {
        /** @description The unique string that identifies the Supporting Document Type resource. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["numbers.v2.regulatory_compliance.supporting_document_type"];
        };
      };
    };
  };
}
