/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/AuthTokens/Promote": {
    /** @description Promote the secondary Auth Token to primary. After promoting the new token, all requests to Twilio using your old primary Auth Token will result in an error. */
    post: operations["UpdateAuthTokenPromotion"];
  };
  "/v1/Credentials": {
  };
  "/v1/Credentials/AWS": {
    /** @description Retrieves a collection of AWS Credentials belonging to the account used to make the request */
    get: operations["ListCredentialAws"];
    /** @description Create a new AWS Credential */
    post: operations["CreateCredentialAws"];
  };
  "/v1/Credentials/AWS/{Sid}": {
    /** @description Fetch the AWS credentials specified by the provided Credential Sid */
    get: operations["FetchCredentialAws"];
    /** @description Modify the properties of a given Account */
    post: operations["UpdateCredentialAws"];
    /** @description Delete a Credential from your account */
    delete: operations["DeleteCredentialAws"];
  };
  "/v1/Credentials/PublicKeys": {
    /** @description Retrieves a collection of Public Key Credentials belonging to the account used to make the request */
    get: operations["ListCredentialPublicKey"];
    /** @description Create a new Public Key Credential */
    post: operations["CreateCredentialPublicKey"];
  };
  "/v1/Credentials/PublicKeys/{Sid}": {
    /** @description Fetch the public key specified by the provided Credential Sid */
    get: operations["FetchCredentialPublicKey"];
    /** @description Modify the properties of a given Account */
    post: operations["UpdateCredentialPublicKey"];
    /** @description Delete a Credential from your account */
    delete: operations["DeleteCredentialPublicKey"];
  };
  "/v1/SafeList/Numbers": {
    /** @description Check if a phone number exists in SafeList. */
    get: operations["FetchSafelist"];
    /** @description Add a new phone number to SafeList. */
    post: operations["CreateSafelist"];
    /** @description Remove a phone number from SafeList. */
    delete: operations["DeleteSafelist"];
  };
  "/v1/AuthTokens/Secondary": {
    /** @description Create a new secondary Auth Token */
    post: operations["CreateSecondaryAuthToken"];
    /** @description Delete the secondary Auth Token from your account */
    delete: operations["DeleteSecondaryAuthToken"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "accounts.v1.auth_token_promotion": {
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that the secondary Auth Token was created for. */
      account_sid?: string | null;
      /** @description The promoted Auth Token that must be used to authenticate future API requests. */
      auth_token?: string | null;
      /**
       * Format: date-time
       * @description The date and time in UTC when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null;
      /**
       * Format: uri
       * @description The URI for this resource, relative to `https://accounts.twilio.com`
       */
      url?: string | null;
    };
    "accounts.v1.credential": Record<string, never>;
    "accounts.v1.credential.credential_aws": {
      /** @description The unique string that we created to identify the AWS resource. */
      sid?: string | null;
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the AWS resource. */
      account_sid?: string | null;
      /** @description The string that you assigned to describe the resource. */
      friendly_name?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_updated?: string | null;
      /**
       * Format: uri
       * @description The URI for this resource, relative to `https://accounts.twilio.com`
       */
      url?: string | null;
    };
    "accounts.v1.credential.credential_public_key": {
      /** @description The unique string that that we created to identify the PublicKey resource. */
      sid?: string | null;
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Credential that the PublicKey resource belongs to. */
      account_sid?: string | null;
      /** @description The string that you assigned to describe the resource. */
      friendly_name?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
       */
      date_updated?: string | null;
      /**
       * Format: uri
       * @description The URI for this resource, relative to `https://accounts.twilio.com`
       */
      url?: string | null;
    };
    "accounts.v1.safelist": {
      /** @description The unique string that we created to identify the SafeList resource. */
      sid?: string | null;
      /** @description The phone number in SafeList. */
      phone_number?: string | null;
    };
    "accounts.v1.secondary_auth_token": {
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that the secondary Auth Token was created for. */
      account_sid?: string | null;
      /**
       * Format: date-time
       * @description The date and time in UTC when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null;
      /**
       * Format: date-time
       * @description The date and time in UTC when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null;
      /** @description The generated secondary Auth Token that can be used to authenticate future API requests. */
      secondary_auth_token?: string | null;
      /**
       * Format: uri
       * @description The URI for this resource, relative to `https://accounts.twilio.com`
       */
      url?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** @description Promote the secondary Auth Token to primary. After promoting the new token, all requests to Twilio using your old primary Auth Token will result in an error. */
  UpdateAuthTokenPromotion: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["accounts.v1.auth_token_promotion"];
        };
      };
    };
  };
  /** @description Retrieves a collection of AWS Credentials belonging to the account used to make the request */
  ListCredentialAws: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            credentials?: components["schemas"]["accounts.v1.credential.credential_aws"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Create a new AWS Credential */
  CreateCredentialAws: {
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description A string that contains the AWS access credentials in the format `<AWS_ACCESS_KEY_ID>:<AWS_SECRET_ACCESS_KEY>`. For example, `AKIAIOSFODNN7EXAMPLE:wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY` */
          Credentials: string;
          /** @description A descriptive string that you create to describe the resource. It can be up to 64 characters long. */
          FriendlyName?: string;
          /** @description The SID of the Subaccount that this Credential should be associated with. Must be a valid Subaccount of the account issuing the request. */
          AccountSid?: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["accounts.v1.credential.credential_aws"];
        };
      };
    };
  };
  /** @description Fetch the AWS credentials specified by the provided Credential Sid */
  FetchCredentialAws: {
    parameters: {
      path: {
        /** @description The Twilio-provided string that uniquely identifies the AWS resource to fetch. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["accounts.v1.credential.credential_aws"];
        };
      };
    };
  };
  /** @description Modify the properties of a given Account */
  UpdateCredentialAws: {
    parameters: {
      path: {
        /** @description The Twilio-provided string that uniquely identifies the AWS resource to update. */
        Sid: string;
      };
    };
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description A descriptive string that you create to describe the resource. It can be up to 64 characters long. */
          FriendlyName?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["accounts.v1.credential.credential_aws"];
        };
      };
    };
  };
  /** @description Delete a Credential from your account */
  DeleteCredentialAws: {
    parameters: {
      path: {
        /** @description The Twilio-provided string that uniquely identifies the AWS resource to delete. */
        Sid: string;
      };
    };
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never;
      };
    };
  };
  /** @description Retrieves a collection of Public Key Credentials belonging to the account used to make the request */
  ListCredentialPublicKey: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number;
        /** @description The page index. This value is simply for client state. */
        Page?: number;
        /** @description The page token. This is provided by the API. */
        PageToken?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            credentials?: components["schemas"]["accounts.v1.credential.credential_public_key"][];
            meta?: {
              /** Format: uri */
              first_page_url?: string;
              /** Format: uri */
              next_page_url?: string | null;
              page?: number;
              page_size?: number;
              /** Format: uri */
              previous_page_url?: string | null;
              /** Format: uri */
              url?: string;
              key?: string;
            };
          };
        };
      };
    };
  };
  /** @description Create a new Public Key Credential */
  CreateCredentialPublicKey: {
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description A URL encoded representation of the public key. For example, `-----BEGIN PUBLIC KEY-----MIIBIjANB.pa9xQIDAQAB-----END PUBLIC KEY-----` */
          PublicKey: string;
          /** @description A descriptive string that you create to describe the resource. It can be up to 64 characters long. */
          FriendlyName?: string;
          /** @description The SID of the Subaccount that this Credential should be associated with. Must be a valid Subaccount of the account issuing the request */
          AccountSid?: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["accounts.v1.credential.credential_public_key"];
        };
      };
    };
  };
  /** @description Fetch the public key specified by the provided Credential Sid */
  FetchCredentialPublicKey: {
    parameters: {
      path: {
        /** @description The Twilio-provided string that uniquely identifies the PublicKey resource to fetch. */
        Sid: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["accounts.v1.credential.credential_public_key"];
        };
      };
    };
  };
  /** @description Modify the properties of a given Account */
  UpdateCredentialPublicKey: {
    parameters: {
      path: {
        /** @description The Twilio-provided string that uniquely identifies the PublicKey resource to update. */
        Sid: string;
      };
    };
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description A descriptive string that you create to describe the resource. It can be up to 64 characters long. */
          FriendlyName?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["accounts.v1.credential.credential_public_key"];
        };
      };
    };
  };
  /** @description Delete a Credential from your account */
  DeleteCredentialPublicKey: {
    parameters: {
      path: {
        /** @description The Twilio-provided string that uniquely identifies the PublicKey resource to delete. */
        Sid: string;
      };
    };
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never;
      };
    };
  };
  /** @description Check if a phone number exists in SafeList. */
  FetchSafelist: {
    parameters: {
      query?: {
        /** @description The phone number to be fetched from SafeList. Phone numbers must be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164). */
        PhoneNumber?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["accounts.v1.safelist"];
        };
      };
    };
  };
  /** @description Add a new phone number to SafeList. */
  CreateSafelist: {
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description The phone number to be added in SafeList. Phone numbers must be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164). */
          PhoneNumber: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["accounts.v1.safelist"];
        };
      };
    };
  };
  /** @description Remove a phone number from SafeList. */
  DeleteSafelist: {
    parameters: {
      query?: {
        /** @description The phone number to be removed from SafeList. Phone numbers must be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164). */
        PhoneNumber?: string;
      };
    };
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never;
      };
    };
  };
  /** @description Create a new secondary Auth Token */
  CreateSecondaryAuthToken: {
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["accounts.v1.secondary_auth_token"];
        };
      };
    };
  };
  /** @description Delete the secondary Auth Token from your account */
  DeleteSecondaryAuthToken: {
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never;
      };
    };
  };
}
